Fix circular dependency introduced in e37dec3 and 2fd2e6d
Commit e37dec3 and 2fd2e6d uses the variable `$::slurm::do_build` in
`::slurm::params` to set the variables
`$::slurm::params::pre_requisite_packages` and
`$::slurm::params::munge_extra_packages`. Because `$::slurm::do_build` is
defined in `::slurm` this introduces a circular dependency.

If running Puppetserver with the setting `strict_variables = true` this results
in a failure:

~~~
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown variable: 'slurm::do_build'. at /etc/puppetlabs/code/environments/production/modules/slurm/manifests/params.pp:29:6 on node whata.name
~~~